apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
  labels:
    app_name: {{ template "coremaker-common-chart.fullname" . }}
    app_version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app_name: {{ template "coremaker-common-chart.fullname" . }}
  template:
    metadata:
      labels:
        app_name: {{ template "coremaker-common-chart.fullname" . }}
        app_version: {{ .Values.image.tag }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
{{- if .Values.initContainers }}
{{- toYaml .Values.initContainers | nindent 8 }}
{{- end }}
{{- if .Values.container.serviceAccount.create }}
      serviceAccountName: {{ template "coremaker-common-chart.fullname" . }}
{{- end }}
      containers:
{{- if .Values.sidecarContainers }}
{{- toYaml .Values.sidecarContainers | nindent 8 }}
{{- end }}
        - name: {{ template "coremaker-common-chart.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BASE_IMAGE
              value: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            - name: CONTAINER_NAME
              value: {{ template "coremaker-common-chart.fullname" . }}
            - name: APP_NAME
              value: {{ template "coremaker-common-chart.fullname" . }}
            - name: APP_VERSION
              value: {{ .Values.image.tag }}
{{- if .Values.container.env }}
{{- range $key, $value := .Values.container.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl (print $value) $ }}"
{{- end }}
{{- end }}
{{- if .Values.container.envFrom }}
{{- range $key, $value := .Values.container.envFrom }}
            - name: {{ $key | quote }}
              valueFrom:
{{ toYaml $value | indent 16 }}
{{- end }}
{{- end }}
          volumeMounts:
{{- if .Values.container.additionalVolumeMounts }}
{{ toYaml .Values.container.additionalVolumeMounts | indent 12 }}
{{- end }}
          ports:
            - name: {{ .Values.container.ports.name }}
              containerPort: {{ .Values.container.ports.port }}
{{- if .Values.container.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.container.livenessProbe | indent 12 }}
{{- end }}
{{- if .Values.container.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.container.readinessProbe | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.container.resources | indent 12 }}
      volumes:
{{- if .Values.additionalVolumes }}
{{ toYaml .Values.additionalVolumes | indent 8 }}
{{- end }}
