{{- if .Values.fluxv2.enabled -}}
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
  namespace: {{ .Values.fluxv2.imageRepository.namespace }}
spec:
  interval: {{ .Values.fluxv2.imageRepository.interval }}
  image: {{ .Values.image.repository }}
  suspend: {{ .Values.fluxv2.imageRepository.suspend }}
  secretRef:
    name: {{ .Values.fluxv2.imageRepository.gcrSecretName }}
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}
{{- end }}