{{- if .Values.container.serviceAccount.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "coremaker-common-chart.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "coremaker-common-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}