{{- if .Values.container.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
rules:
{{- with .Values.container.serviceAccount.roleRules }}
{{ toYaml . | indent 0 }}
{{- end}}
{{- end -}}