{{- if .Values.container.backend.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}-service-backend
spec:
  timeoutSec: {{ .Values.container.backend.timeout }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.container.backend.connectionDrainingTimeoutSec }}
{{- end }}