apiVersion: v1
kind: Service
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
  annotations:
{{- if .Values.container.backend.enabled }}
    cloud.google.com/backend-config: '{"ports": {"http":"{{ template "coremaker-common-chart.fullname" . }}-service-backend"}}'
{{- end }}
  labels:
    app_name: {{ template "coremaker-common-chart.fullname" . }}
    app_version: {{ .Chart.Version }}
    app: {{ template "coremaker-common-chart.fullname" . }}
    version: v1

spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
{{- if .Values.container.additionalServicePorts }}
{{ toYaml .Values.container.additionalServicePorts | indent 4 }}
{{- end }} 
    - name: http
      port: 80
      targetPort: {{ .Values.container.ports.port }}
  selector:
    app_name: {{ template "coremaker-common-chart.fullname" . }}
{{- if .Values.istio.selectors }}
    app: {{ template "coremaker-common-chart.fullname" . }}
    version: v1
{{- end }} 
