{{- if .Values.container.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
  labels:
    app: {{ template "coremaker-common-chart.fullname" . }}
{{- if .Values.container.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.container.serviceAccount.annotations | indent 8 }}
{{- end }}
{{- end -}}