{{- if .Values.container.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}
  labels:
    app: {{ template "coremaker-common-chart.fullname" . }}
{{- end -}}