{{- if .Values.container.backend.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "coremaker-common-chart.fullname" . }}-service-backend
spec:
  timeoutSec: {{ .Values.container.backend.timeout }}
  connectionDraining:
    drainingTimeoutSec: {{ .Values.container.backend.connectionDrainingTimeoutSec }}
  healthCheck:
    type: HTTP
    requestPath: {{ .Values.container.livenessProbe.httpGet.path }}
    port: {{ .Values.container.ports.port }}
{{- if .Values.container.backend.customRequest.headers }}
  customRequestHeaders:
    headers:
{{ toYaml .Values.container.backend.customRequest.headers | indent 4 }}
{{- end }}
{{- end }}