apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.container.backend.enabled -}}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"{{ .Chart.Name }}-service-backend"}}'
{{- end }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Chart.Version }}

spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.container.port }}
  selector:
    app_name: {{ .Chart.Name }}